monthly_model <- tibble(
  "month" = as.Date("1970-01-01"), 
  "retention_month" = as.Date("1970-01-01"), 
  "starting" = 1,
  "churned" = 0,
  "returning" =0,
  "new"=0,
  "resurrected"=0,
  "ending"=0,
  "shares_out"=0,
  "shares_in"=0,
  "impressions_out"=0,
  "impressions_in"=0,
  "engagements"=0,
  "transactions"=0,
  "revenue"=0,
  "traffic_source"="",
  "network_side"="")

monthly_model<- monthly_model %>%
  filter(month>=start_month)

monthly_model <- add_members (
  monthly_model,
  small_side,
  "organic",
  starting_small,
  OR_organic_small,
  LTV_month1_churn_small,
  LTV_ongoing_churn_small,
  LTV_month1_churn_big,
  LTV_ongoing_churn_big,
  NE_small_shares_out,
  NE_small_shares_in,
  NE_big_shares_out,
  NE_big_shares_in,
  NE_small_shares_out_audience ,
  NE_small_shares_in_audience,
  NE_big_shares_out_audience ,
  NE_big_shares_in_audience,
  FC_shared_small_vsmall,
  FC_shared_big_vsmall,
  FC_shared_transactions_vsmall,
  FC_shared_engagements_vsmall,
  FC_shared_small_vbig,
  FC_shared_big_vbig,
  FC_shared_transactions_vbig,
  FC_shared_engagements_vbig,
  Rev_subscription_rate,
  Rev_rev_per_transaction,
  start_month,
  ending_month
)

monthly_model <- add_members (
  monthly_model,
  small_side,
  "paid",
  starting_small,
  OR_paid_small,
  LTV_month1_churn_small,
  LTV_ongoing_churn_small,
  LTV_month1_churn_big,
  LTV_ongoing_churn_big,
  NE_small_shares_out,
  NE_small_shares_in,
  NE_big_shares_out,
  NE_big_shares_in,
  NE_small_shares_out_audience ,
  NE_small_shares_in_audience,
  NE_big_shares_out_audience ,
  NE_big_shares_in_audience,
  FC_shared_small_vsmall,
  FC_shared_big_vsmall,
  FC_shared_transactions_vsmall,
  FC_shared_engagements_vsmall,
  FC_shared_small_vbig,
  FC_shared_big_vbig,
  FC_shared_transactions_vbig,
  FC_shared_engagements_vbig,
  Rev_subscription_rate,
  Rev_rev_per_transaction,
  start_month,
  ending_month
)

monthly_model <- add_members (
  monthly_model,
  big_side,
  "organic",
  starting_big,
  OR_organic_big,
  LTV_month1_churn_small,
  LTV_ongoing_churn_small,
  LTV_month1_churn_big,
  LTV_ongoing_churn_big,
  NE_small_shares_out,
  NE_small_shares_in,
  NE_big_shares_out,
  NE_big_shares_in,
  NE_small_shares_out_audience ,
  NE_small_shares_in_audience,
  NE_big_shares_out_audience ,
  NE_big_shares_in_audience,
  FC_shared_small_vsmall,
  FC_shared_big_vsmall,
  FC_shared_transactions_vsmall,
  FC_shared_engagements_vsmall,
  FC_shared_small_vbig,
  FC_shared_big_vbig,
  FC_shared_transactions_vbig,
  FC_shared_engagements_vbig,
  Rev_subscription_rate,
  Rev_rev_per_transaction,
  start_month,
  ending_month
)


monthly_model <- add_members (
  monthly_model,
  big_side,
  "paid",
  starting_big,
  OR_paid_big,
  LTV_month1_churn_small,
  LTV_ongoing_churn_small,
  LTV_month1_churn_big,
  LTV_ongoing_churn_big,
  NE_small_shares_out,
  NE_small_shares_in,
  NE_big_shares_out,
  NE_big_shares_in,
  NE_small_shares_out_audience ,
  NE_small_shares_in_audience,
  NE_big_shares_out_audience ,
  NE_big_shares_in_audience,
  FC_shared_small_vsmall,
  FC_shared_big_vsmall,
  FC_shared_transactions_vsmall,
  FC_shared_engagements_vsmall,
  FC_shared_small_vbig,
  FC_shared_big_vbig,
  FC_shared_transactions_vbig,
  FC_shared_engagements_vbig,
  Rev_subscription_rate,
  Rev_rev_per_transaction,
  start_month,
  ending_month
)

monthly_model <- add_paid_shares(monthly_model,OR_paid_big_CPM,OR_paid_big_usd,big_side,paste(company_name," - paid"),start_month,ending_month)
monthly_model <- add_paid_shares(monthly_model,OR_paid_small_CPM,OR_paid_small_usd,small_side,paste(company_name," - paid"),start_month,ending_month)

#monthly_model <- add_subscription_revenue( monthly_model,Rev_transactions_per_month,Rev_rev_per_transaction,Rev_subscription_rate,Rev_take_rate, start_month,ending_month,big_side)

